resource "random_pet" "my-pet" {

  length = var.length
}

output "pet-name" {

  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
  filename        = "/home/cshakya/Music/message.txt"
  file_permission = 0755
  content         = "Welcome to Learndevops29 "
}

output "welcome_message" {
	value = local_file.welcome.content
}
